import { Link } from "wouter";
import { ArrowLeft } from "lucide-react";

const COMPANY = "BetPulse"; // TODO: replace with legal company name
const CONTACT = "support@betpulse.io"; // TODO: replace with contact email
const JURISDICTION = "the State of Delaware, United States"; // TODO: replace
const EFFECTIVE = "April 2026";

function Page({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <div className="min-h-screen bg-background p-4 md:p-8">
      <div className="max-w-3xl mx-auto">
        <Link href="/dashboard">
          <button className="text-muted-foreground hover:text-foreground text-sm flex items-center gap-2 mb-6">
            <ArrowLeft className="w-4 h-4" /> Back
          </button>
        </Link>
        <h1 className="text-3xl font-bold uppercase tracking-wider text-foreground mb-2">{title}</h1>
        <p className="text-xs text-muted-foreground mb-8">Effective {EFFECTIVE}</p>
        <div className="prose prose-invert max-w-none text-sm text-foreground/90 space-y-5 leading-relaxed">
          {children}
        </div>
      </div>
    </div>
  );
}

export function Privacy() {
  return (
    <Page title="Privacy Policy">
      <p>
        {COMPANY} ("we", "us") respects your privacy. This policy explains what we collect, how we use it,
        and your rights. By using the service you agree to this policy.
      </p>
      <h2 className="text-base font-bold uppercase tracking-wider text-primary">What we collect</h2>
      <ul className="list-disc pl-5 space-y-1">
        <li>Account: email address, hashed password.</li>
        <li>Bets and bankroll data you log into the app.</li>
        <li>Subscription and billing identifiers (handled by Stripe; we never see your card).</li>
        <li>Operational logs (IP, request paths) for security and debugging.</li>
      </ul>
      <h2 className="text-base font-bold uppercase tracking-wider text-primary">How we use it</h2>
      <ul className="list-disc pl-5 space-y-1">
        <li>To run the app, compute your stats and AI insights, and send you reports you opted into.</li>
        <li>To process payments via Stripe.</li>
        <li>To maintain security (rate limiting, abuse prevention).</li>
      </ul>
      <p>
        We do <strong>not</strong> sell your data. We do not share it with third parties except service
        providers required to run the app (database hosting, email sending, payment processing).
      </p>
      <h2 className="text-base font-bold uppercase tracking-wider text-primary">Your rights</h2>
      <p>
        You can export all your data or permanently delete your account from Settings at any time.
        EU/UK/California residents may have additional rights under GDPR/CCPA — contact {CONTACT}.
      </p>
      <h2 className="text-base font-bold uppercase tracking-wider text-primary">Cookies</h2>
      <p>
        We use a single authentication token in local storage to keep you signed in. No advertising cookies.
      </p>
      <h2 className="text-base font-bold uppercase tracking-wider text-primary">Contact</h2>
      <p>Questions? Email {CONTACT}.</p>
    </Page>
  );
}

export function Terms() {
  return (
    <Page title="Terms of Service">
      <p>
        By creating an account with {COMPANY}, you agree to these terms. If you do not agree, do not use the service.
      </p>
      <h2 className="text-base font-bold uppercase tracking-wider text-primary">What this service is</h2>
      <p>
        BetPulse is a personal behavioral analytics tool. It helps you track bets you have already
        placed elsewhere and gives you AI-driven feedback on your patterns. We do <strong>not</strong>
        offer betting picks, advice on what to bet, or any form of gambling. We do not place bets on
        your behalf.
      </p>
      <h2 className="text-base font-bold uppercase tracking-wider text-primary">Eligibility</h2>
      <p>
        You must be 18 years or older (or legal age in your jurisdiction) to use this service. You are
        solely responsible for complying with the laws in your jurisdiction regarding sports betting.
      </p>
      <h2 className="text-base font-bold uppercase tracking-wider text-primary">No financial advice</h2>
      <p>
        Insights generated by the app are informational only. They are not financial advice, investment
        advice, or guarantees of future results. Past performance is not indicative of future results.
      </p>
      <h2 className="text-base font-bold uppercase tracking-wider text-primary">Subscriptions</h2>
      <p>
        Pro is billed monthly. You may cancel anytime from Settings; access continues until the end of
        the paid period. Trials convert automatically to paid subscriptions unless cancelled before the
        trial ends.
      </p>
      <h2 className="text-base font-bold uppercase tracking-wider text-primary">Account termination</h2>
      <p>
        We may suspend accounts that abuse the service. You may delete your account at any time from Settings.
      </p>
      <h2 className="text-base font-bold uppercase tracking-wider text-primary">Disclaimer of warranties</h2>
      <p>
        The service is provided "as is" without warranties of any kind. To the maximum extent permitted
        by law, {COMPANY} disclaims all warranties and is not liable for losses related to your betting
        activity.
      </p>
      <h2 className="text-base font-bold uppercase tracking-wider text-primary">Responsible gambling</h2>
      <p>
        If you or someone you know has a gambling problem, call 1-800-GAMBLER (US) or visit
        begambleaware.org. Use this app to <em>moderate</em> your behavior, not to enable it.
      </p>
      <h2 className="text-base font-bold uppercase tracking-wider text-primary">Governing law</h2>
      <p>These terms are governed by the laws of {JURISDICTION}.</p>
      <p>Contact: {CONTACT}.</p>
    </Page>
  );
}
